name: Deploy Backend

on:
  workflow_dispatch:

jobs:
  build:
    name: echo
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          echo ${{ secrets.DATABASE_URL }}
